import * as fs from 'node:fs';
import * as path from 'node:path';
import { extraCflags, shellSplit } from './args';
import { exec } from './exec';
import type { CompdbSource, Context } from './types';

export interface CompdbEntry {
  directory: string;
  file: string;
  arguments: string[];
}

export interface CompdbResult {
  method: CompdbSource; // 実際に使った方式
  entries: number;
  note?: string;
}

export const CLANGD_MARKER = '# generated by c42check';

export { shellSplit };

const COMPILER_RE = /^(?:.*\/)?(?:cc|c99|gcc|clang|(?:gcc|clang)-\d+|[\w.-]+-gcc)$/;
const KEEP_WITH_VALUE = new Set(['-I', '-D', '-U', '-include', '-isystem', '-iquote', '-idirafter']);
const SKIP_WITH_VALUE = new Set(['-o', '-MF', '-MT', '-MQ']);
const KEEP_PREFIX = /^-(I|D|U|O|g|std=|m|f|pthread|isystem|iquote|idirafter|include|W(?!l,))/;

/**
 * `make -n -B -w` の出力から compile_commands の entries を作る。
 * `-c` / `-o` / 出力系 (-MF 等) / 入力ファイル / リンク系を取り除き、フラグだけを残す。
 */
export function parseMakeDryRun(output: string, root: string): CompdbEntry[] {
  // 行継続 (\ + 改行) を結合
  const lines = output.replace(/\\\r?\n/g, ' ').split('\n');
  const stack: string[] = [root];
  const entries: CompdbEntry[] = [];
  const seen = new Set<string>();
  for (const line of lines) {
    const enter = /Entering directory ['`](.+)'/.exec(line);
    if (enter) {
      stack.push(enter[1]);
      continue;
    }
    if (/Leaving directory/.test(line)) {
      if (stack.length > 1) stack.pop();
      continue;
    }
    const dir = stack[stack.length - 1];
    // && ; || | で分けて、コンパイラ呼び出しの部分だけを見る
    for (const seg of line.split(/&&|\|\||;|\|/)) {
      const tokens = shellSplit(seg.trim());
      while (tokens.length && /^\w+=/.test(tokens[0])) tokens.shift();
      if (!tokens.length || !COMPILER_RE.test(tokens[0])) continue;
      const compiler = tokens[0];
      const files = tokens.slice(1).filter((t, i, a) => /\.c$/.test(t) && !SKIP_WITH_VALUE.has(a[i - 1] ?? ''));
      if (!files.length) continue;
      const flags: string[] = [];
      for (let i = 1; i < tokens.length; i++) {
        const t = tokens[i];
        if (SKIP_WITH_VALUE.has(t)) {
          i++;
        } else if (KEEP_WITH_VALUE.has(t)) {
          flags.push(t, tokens[++i] ?? '');
        } else if (t.startsWith('-') && KEEP_PREFIX.test(t)) {
          flags.push(t);
        }
      }
      for (const f of files) {
        const abs = path.resolve(dir, f);
        const key = `${dir}\0${abs}`;
        if (seen.has(key)) continue;
        seen.add(key);
        entries.push({ directory: dir, file: abs, arguments: [compiler, ...flags, '-c', abs] });
      }
    }
  }
  return entries;
}

function includeFlags(ctx: Context): string[] {
  return ctx.includeDirs.map((d) => `-I${d}`);
}

export function entriesFromFiles(ctx: Context): CompdbEntry[] {
  const cc = ctx.tools.cc ?? 'clang';
  const inc = includeFlags(ctx);
  return ctx.sources.map((file) => ({
    directory: ctx.root,
    file,
    arguments: [cc, ...inc, ...extraCflags(ctx), '-c', file],
  }));
}

async function entriesFromMakeN(ctx: Context): Promise<CompdbEntry[]> {
  if (!ctx.tools.make) return [];
  const r = await exec(ctx.tools.make, ['-n', '-B', '-w'], {
    cwd: ctx.targetRoot,
    timeoutMs: 60_000,
    signal: ctx.signal,
    env: { ...process.env, LC_ALL: 'C' },
  });
  // Makefile のフラグに、設定の cflags を足す (clangd が -D などを同じように解釈できるように)
  const extra = extraCflags(ctx);
  return parseMakeDryRun(r.output, ctx.targetRoot).map((e) => {
    const at = e.arguments.lastIndexOf('-c');
    return extra.length === 0 || at < 0 ? e : { ...e, arguments: [...e.arguments.slice(0, at), ...extra, ...e.arguments.slice(at)] };
  });
}

async function entriesFromClangMJ(ctx: Context): Promise<CompdbEntry[]> {
  const cc = ctx.tools.cc;
  if (!cc) return [];
  const fragDir = path.join(ctx.workDir, 'compdb');
  fs.mkdirSync(fragDir, { recursive: true });
  const inc = includeFlags(ctx);
  const entries: CompdbEntry[] = [];
  for (const [i, file] of ctx.sources.entries()) {
    const frag = path.join(fragDir, `${i}.json`);
    await exec(cc, ['-MJ', frag, '-fsyntax-only', ...inc, ...extraCflags(ctx), file], {
      cwd: ctx.root,
      timeoutMs: 30_000,
      signal: ctx.signal,
    });
    try {
      const text = fs.readFileSync(frag, 'utf8').trim().replace(/,$/, '');
      const e = JSON.parse(text) as CompdbEntry;
      if (e.arguments) entries.push({ directory: e.directory, file: e.file, arguments: e.arguments });
    } catch {
      /* 断片が作れなかったファイルは files 方式で補う */
      entries.push(...entriesFromFiles({ ...ctx, sources: [file] }));
    }
  }
  fs.rmSync(fragDir, { recursive: true, force: true });
  return entries;
}

/** compile_commands.json をワークスペースルートに書く。 */
export async function generateCompdb(ctx: Context): Promise<CompdbResult> {
  const want = ctx.settings.compdbSource;
  let method: CompdbSource = want;
  let entries: CompdbEntry[] = [];
  let note: string | undefined;

  const tryMake = want === 'make-n' || (want === 'auto' && ctx.hasMakefile);
  if (tryMake) {
    entries = await entriesFromMakeN(ctx);
    method = 'make-n';
    if (!entries.length) {
      note = 'make -n から .c のコンパイル行を取得できなかったため files 方式に切り替えました';
      method = 'files';
    }
  } else if (want === 'clang-MJ') {
    entries = await entriesFromClangMJ(ctx);
    if (!entries.length) {
      note = 'clang -MJ で生成できなかったため files 方式に切り替えました';
      method = 'files';
    }
  } else {
    method = 'files';
  }
  if (method === 'files' && !entries.length) entries = entriesFromFiles(ctx);

  // mainFile をテスト用の翻訳単位として compile_commands に含める (設定で切り替え)
  if (ctx.settings.compdbIncludeMain && ctx.mainFile && !entries.some((e) => e.file === ctx.mainFile)) {
    const base = entriesFromFiles({ ...ctx, sources: [ctx.mainFile] });
    entries.push(...base);
  }

  fs.writeFileSync(path.join(ctx.root, 'compile_commands.json'), JSON.stringify(entries, null, 2) + '\n');
  return { method, entries: entries.length, note };
}

export function clangdContent(): string {
  return [
    `${CLANGD_MARKER} — このコメント行を消すと、以降は上書きしません`,
    '# clangd 内蔵の clang-tidy は編集中の参考表示です。合否判定は 42 Check の clang-tidy-12 の結果が正です。',
    'CompileFlags:',
    '  Add: [-Wall, -Wextra, -Wshadow, -Wconversion]',
    'Diagnostics:',
    '  ClangTidy:',
    '    Add: [clang-analyzer-*, bugprone-*]',
    '',
  ].join('\n');
}

/** .clangd を書く。自分が作ったもの以外は上書きしない。戻り値は書いたか。 */
export function generateClangd(root: string): { written: boolean; reason?: string } {
  const file = path.join(root, '.clangd');
  if (fs.existsSync(file)) {
    const head = fs.readFileSync(file, 'utf8').split('\n', 1)[0];
    if (!head.startsWith(CLANGD_MARKER)) {
      return { written: false, reason: '既存の .clangd (42 Check 製ではない) があるため上書きしませんでした' };
    }
  }
  fs.writeFileSync(file, clangdContent());
  return { written: true };
}
